services:
  ravendb:
    image: ravendb/ravendb:latest
    container_name: ravendb
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_Integrations_PostgreSQL_Enabled=false
      - RAVEN_Features_Availability=Experimental
    ports:
      - "8080:8080"
    volumes:
      - ./RavenData:/var/lib/ravendb/data
    restart: unless-stopped

  producer:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    container_name: producer
    working_dir: /src
    volumes:
      - ./Producer:/src
    command: dotnet watch run --urls=http://+:5095
    environment:
      - RAVEN_URL=http://ravendb:8080
      - RAVEN_DATABASE=Hackathon
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "5095:5095"
    restart: unless-stopped
    depends_on:
      - ravendb

  consumer:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    container_name: consumer
    working_dir: /src
    volumes:
      - ./Consumer:/src
    command: dotnet watch run --urls=http://+:5188
    ports:
      - "5188:5188"
    restart: unless-stopped
    depends_on:
      - ravendb
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.87.0
    container_name: otel-collector
    volumes:
      - ./telemetry/otel/otel.yaml:/etc/otel.yaml:ro
    command: [ "--config", "/etc/otel.yaml" ]
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8889:8889"   # Prometheus scraping
    restart: unless-stopped
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./telemetry/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    
  tempo:
    image: grafana/tempo:2.6.1
    container_name: tempo
    command: [ "-config.file=/etc/tempo/tempo.yml" ]
    volumes:
      - ./telemetry/tempo/tempo.yaml:/etc/tempo/tempo.yml
      - ./telemetry/tempo/data:/var/tempo
    ports:
      - "3200:3200"   # Tempo HTTP API
      - "4319:4317"   # OTLP gRPC (optional if collector forwards internally)
      - "4320:4318"   # OTLP HTTP (optional)
    restart: unless-stopped
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
    ports:
      - "3000:3000"
    volumes:
      - ./telemetry/grafana/custom.ini:/etc/grafana/custom.ini:ro
      - ./telemetry/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./telemetry/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./telemetry/grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki
      - tempo

volumes:
  ravendb_data: